# 2. 사이킷런으로 시작하는 머신러닝

## 붓꽃(iris) 품종 예측하기

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

In [2]:
iris = load_iris()

iris_data = iris.data       # X
iris_label = iris.target    # y

print('iris target 값:', iris_label, '\niris target명:', iris.target_names)

iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [3]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [4]:
# DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(random_state=11)
clf_dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [5]:
y_pred = clf_dt.predict(X_test)

In [6]:
from sklearn.metrics import accuracy_score

print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test, y_pred)))

예측 정확도 : 0.9333


## 사이킷런의 기반 프레임워크 익히기

In [7]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [8]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들 :', keys)

붓꽃 데이터 세트의 키들 : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


### Model Selection 모듈

OverFitting을 방지하기 위해 테스트 데이터에 대해 테스트를 진행하지만, 이 과적합을 막기위한 노력은 오히려 고정된 Test set에 대해서만 높은 정확도를 나타내는 방향으로 유도될 수 있음 -> 교차검증 필요!

K-폴드 교차검증 : K개의 데이터 폴드 세트를 만들어서 K번만큼 검증셋과 훈련셋을 바꿔가며 진행

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
clf_dt = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []

In [10]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    clf_dt.fit(X_train, y_train)
    y_pred = clf_dt.predict(X_test)
    n_iter += 1
    
    accuracy = np.round(accuracy_score(y_pred, y_test), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    print('\n#{} 교차 검증 정확도: {}, 학습 데이터 크기: {}, 검증 데이터 크기: {}'.format(n_iter, accuracy, train_size, test_size))
    print('{} 검증 세트 인덱스: {}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
print('\n평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

평균 검증 정확도: 0.9


Stratifired K-Fold : 불균형한 분포도를 가진 검증 데이터 집합이 안나오도록 균형적으로 반영

In [11]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_itier = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증: {}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 6
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 7
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 8
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [12]:
# 교차 검증을 보다 간편하게 -> cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate      # cross_validate는 cross_val_score와 유사하지만 여러 평가지표 반환가능.
from sklearn.datasets import load_iris

iris_data = load_iris()
clf_dt = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# accuracy에 대해 교차검증세트 3개
scores = cross_val_score(clf_dt, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [13]:
# GridSearchCV -> 교차검증과 최적 하이퍼파라미터 튜닝을 한번에
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=21)

clf_dt = DecisionTreeClassifier()

parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [15]:
import pandas as pd

grid_dt = GridSearchCV(clf_dt, param_grid=parameters, cv=3, refit=True)     
# refit=True(디폴트)는 가장 좋은 파라미터 설정으로 재학습
# cv = 3은 3개의 데이터셋으로 나누어 학습

grid_dt.fit(X_train, y_train)

scores_df = pd.DataFrame(grid_dt.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.683333                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.683333                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.975000                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.975000                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.991667                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.991667                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700              0.675              0.675  
1              0.700              0.675              0.675  
2              0.950              0.975              1.000  
3              0.950              0.975              1.000  
4              0.975              1.000              1.000  
5              0.975              1.000              1.000

In [16]:
print('GridSearchCV 최적 파라미터:', grid_dt.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dt.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9917


In [17]:
estimator = grid_dt.best_estimator_

pred = estimator.predict(X_test)
print('테스트 데이터 셋 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 셋 정확도 : 0.9333


## 데이터 전처리

### 레이블 인코딩

In [20]:
# 텍스트 데이터를 종류별로 하나씩 할당하는 방법
# 하지만 높은 숫자가 할당되면 그만큼 더 많은 가중치를 의미 -> 트리계열 알고리즘 제외하고는 문제 있음
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_)
print('인코딩 원본값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
인코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원-핫 인코딩

In [21]:
# 더미변수와 비슷
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 원-핫 인코딩 전에 숫자로 바꿔야함 -> LabelEncoder 활용
encoder=  LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1)       # 2차원 데이터로 변환

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터\n', oh_labels.toarray(), '\n원-핫 인코딩 데이터 차원\n', oh_labels.shape)

원-핫 인코딩 데이터
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]] 
원-핫 인코딩 데이터 차원
 (8, 6)


In [22]:
# 원-핫 인코딩을 더 쉽게 진행하는 API
import pandas as pd

df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## 스케일링

### StandardScaler

In [24]:
# 개별 피처를 평균이 0이고, 분산이 1인 값으로 변환
# RBF 커널을 이용하는 SVM, 선형회귀, 로지스틱회귀 등에 필요(데이터가 가우시안분포를 따른다고 가정하기 때문)
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값\n', iris_df.mean(), '\n\nfeature 들의 분산 값\n', iris_df.var())

feature 들의 평균 값
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64 

feature 들의 분산 값
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값\n', iris_df_scaled.mean(), '\n\nfeature 들의 분산 값\n', iris_df_scaled.var())

feature 들의 평균 값
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64 

feature 들의 분산 값
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler

In [29]:
# (x - min)/(max - min) 을 통해 0~1 사이의 값으로 변환. 가우시안 분포가 아닐 경우에 활용
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최솟값\n', iris_df_scaled.min(), '\n\nfeature 들의 최댓값\n', iris_df_scaled.max())

feature 들의 최솟값
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64 

feature 들의 최댓값
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 스케일링 변환시 유의점

In [33]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [37]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2), '\nScaled train_array 데이터', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10] 
Scaled train_array 데이터 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [38]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2), '\nScaled test_array 데이터', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5] 
Scaled test_array 데이터 [0.  0.2 0.4 0.6 0.8 1. ]
